#!/usr/bin/python
# -*- coding: UTF-8 -*-

CITY_IATA = {
    "AAL": "Aalborg",
    "ABE": "Allentown",
    "ABJ": "Abidjan",
    "ABQ": "Albuquerque",
    "ABR": "Aberdeen",
    "ABV": "Abuja",
    "ABZ": "Aberseen",
    "ACC": "Accra",
    "ACE": "Lanzarota",
    "ACH": "Altenrhein",
    "ACK": "Nantucket",
    "ACV": "Arcata",
    "ADA": "Adana",
    "ADB": "Izmir Adnan Mende",
    "ADD": "Addis Ababa",
    "ADL": "Adelaide",
    "AGB": "Munich Augsburg",
    "AGP": "Malaga",
    "AHO": "Alghero",
    "AIY": "Atlantic City",
    "AJA": "Ajaccio",
    "AKL": "Auckland",
    "ALA": "Almaty",
    "ALB": "Albany",
    "ALC": "Alicante",
    "ALG": "Algiers",
    "ALO": "Waterloo",
    "ALW": "Walla Walla",
    "ALY": "Alexandriai",
    "AMA": "Amarillo",
    "AMD": "Ahmedabad",
    "AMI": "Mataram",
    "AMM": "Amman",
    "AMS": "Amsterdam",
    "ANC": "Anchorage",
    "ANK": "Ankara",
    "ANR": "Antwerp",
    "AOI": "Ancona",
    "AOR": "Alor Setar",
    "ASB": "Ashgabat",
    "ASE": "Aspen",
    "ASM": "Asmara",
    "ASR": "Kayseri",
    "ATH": "Athens",
    "ATL": "Atlanta",
    "ATW": "Appleton",
    "ATY": "Watertown",
    "AUA": "Aruba",
    "AUG": "Augusta",
    "AUH": "Abu Dhabi",
    "AUS": "Austin",
    "AVN": "Avignon",
    "AVP": "Wilkes-Barre",
    "AYT": "Antalya",
    "AZO": "Kalamazoo",
    "BAH": "Bahrain",
    "BAK": "Baku",
    "BCD": "Bacolod",
    "BCN": "Barcelona",
    "BDL": "Hartford Bradley",
    "BDS": "Brindisi",
    "BEG": "Belgrade",
    "BER": "Berlin",
    "BES": "Brest",
    "BEY": "Beirut",
    "BFL": "Bakersfield",
    "BFS": "Belfast",
    "BGF": "Bangui",
    "BGM": "Binghamton",
    "BGO": "Bergen",
    "BGR": "Bangor",
    "BHD": "Belfast City Apt",
    "BHM": "Birmingham",
    "BHX": "Birmingham",
    "BIA": "Bastia",
    "BIL": "Billings",
    "BIO": "Bilbao",
    "BIQ": "Biarritz",
    "BJI": "Bemidji",
    "BJV": "Bodrum Milas",
    "BKI": "Kota Kinabalu",
    "BKK": "Bangkok",
    "BKO": "Bamako",
    "BLI": "Bellinghan",
    "BLL": "Billund",
    "BLQ": "Bologna",
    "BLR": "Bangalore",
    "BMI": "Bloomington",
    "BNA": "Nashville",
    "BNE": "Brisbane",
    "BOD": "Bordeauxtz",
    "BOG": "Bogota",
    "BOI": "Boise",
    "BOM": "Mumbai",
    "BON": "Bonaire",
    "BOS": "Boston",
    "BPN": "Balikpapan",
    "BRD": "Brainerd",
    "BRE": "Bremen",
    "BRI": "Bari",
    "BRN": "Berne",
    "BRS": "Bristol",
    "BRU": "Brussel",
    "BSL": "Basel",
    "BTM": "Butte",
    "BTR": "Baton Rouge",
    "BTU": "Bintulu",
    "BTV": "Burlington",
    "BUD": "Budapest",
    "BUE": "Buenos Aires",
    "BUF": "Buffalo",
    "BUH": "Bucharest",
    "BUR": "Burbank",
    "BWI": "Baltimore",
    "BWN": "Bandar Seribegaw",
    "BXU": "Butuan",
    "BZN": "Bozeman",
    "BZV": "Brazzaville",
    "CAE": "Columbia",
    "CAG": "Cagliari",
    "CAI": "Cairo",
    "CAK": "Akron",
    "CAS": "Casablanca",
    "CAY": "Cayenne",
    "CBO": "Cotabato",
    "CBR": "Canberra",
    "CCJ": "Kozhikode",
    "CCS": "Caracas",
    "CCU": "Calcutta",
    "CDR": "Chadron",
    "CEB": "Cebu",
    "CEC": "Crescent City",
    "CEI": "Chiang Rai",
    "CFR": "Caen",
    "CGK": "Jakarta",
    "CGN": "Cologne",
    "CGP": "Chittagong",
    "CGY": "Cagayan De Oro",
    "CHA": "Chattanooga",
    "CHC": "Christchurch",
    "CHI": "Chicago",
    "CHO": "Charlottesville",
    "CHS": "Charleston,SC",
    "CIC": "Chico",
    "CID": "Cedar Rapids",
    "CJJ": "Cheong Ju City",
    "CJU": "Cheju",
    "CKY": "Conakry",
    "CLD": "San Diego Carlsbad",
    "CLE": "Cleveland",
    "CLM": "Port Angeles",
    "CLT": "Charlotte",
    "CLY": "Calvi",
    "CMB": "Colombo",
    "CMH": "Columbus",
    "CMI": "Champaign",
    "CMN": "Mohammed V",
    "CMX": "Hancock",
    "CNS": "Cairns",
    "CNX": "Chiang Mai",
    "COK": "Cochin",
    "COO": "Cotonou",
    "COS": "Colorado Springs",
    "CPH": "Copenhagen",
    "CPT": "Cape Town",
    "CRV": "Crotone",
    "CRW": "Charieston",
    "CSG": "Columbus（GA）",
    "CTA": "Catania",
    "CUR": "Curacao",
    "CVG": "Cincinnati",
    "CWA": "Wausau",
    "CWL": "Cardiff",
    "DAC": "Dhaka",
    "DAM": "Damascus",
    "DAR": "Dar Es Salaam",
    "DAY": "Dayton",
    "DBQ": "Dubugui",
    "DBV": "Dubrovnik",
    "DCA": "Washington Ronald",
    "DDC": "Dodge City",
    "DEL": "Delhi",
    "DEN": "Denver",
    "DFW": "Dallas",
    "DGT": "Dumaguete",
    "DHN": "Dothan",
    "DIY": "Diyarbakir",
    "DKR": "Dakar",
    "DLA": "Douala",
    "DLH": "Duluth",
    "DLM": "Dalaman",
    "DMM": "Dammam",
    "DNZ": "Denizli",
    "DOH": "Doha",
    "DPL": "Dipolog",
    "DPS": "Bali",
    "DRS": "Dresden",
    "DRW": "Darwin",
    "DSM": "Des Moines",
    "DTW": "Detroit",
    "DUB": "Dublin",
    "DUD": "Dunedin",
    "DUS": "Dusseldorf",
    "DVO": "Davao",
    "DXB": "Dubai",
    "EAT": "Wenatchee",
    "EAU": "Eau Claire",
    "EBB": "Entebbe/Kampala",
    "ECN": "Ercan",
    "EDI": "Edinburgh",
    "EDO": "Edremit/Korfez",
    "EGE": "Vail",
    "EIN": "Eindhoven",
    "ERI": "Erie",
    "ERZ": "Erzurum",
    "ESC": "Escanada",
    "ESF": "Alexandria",
    "ETZ": "Metz-Nancy",
    "EUG": "Eugene",
    "EUS": "Joensuu",
    "EVN": "Yerevan",
    "EVV": "Evansville",
    "EWR": "Newark",
    "EZE": "Buenos Aires",
    "FAI": "Fairbanks",
    "FAO": "Faro",
    "FAR": "Fargo",
    "FAT": "Fresno",
    "FCA": "Kalispell",
    "FDF": "Fort de France",
    "FDH": "Friedrichshafen",
    "FIH": "Kinshasa",
    "FKS": "Fukushima",
    "FLL": "Fort Lauderdale",
    "FLR": "Florencei",
    "FMO": "Munster",
    "FNC": "Funchal",
    "FNT": "Flint",
    "FOD": "Fort Dodge",
    "FRA": "Frankfurt",
    "FRU": "Bishkek",
    "FSD": "Sious Falls",
    "FSM": "Fort Smith",
    "FUE": "Fuerteventura",
    "FUK": "Fukuoka",
    "FWA": "Fort Wayne",
    "FYV": "Fayetteville",
    "GCN": "Grand Canyon",
    "GDN": "Gdansk",
    "GEG": "Spokane",
    "GES": "General Santos",
    "GFK": "Grand Forks",
    "GJT": "Grand Junction",
    "GLA": "Glasgow",
    "GLH": "Greenville",
    "GNB": "Grenoble",
    "GOA": "Genoa",
    "GOI": "Goa",
    "GOJ": "Nizhniy Novgorod",
    "GOT": "Gothenburg",
    "GPT": "Gulfport",
    "GPZ": "Grand Rapids",
    "GRB": "Green Bay",
    "GRR": "Grand Rapids",
    "GRZ": "Graz",
    "GSO": "Greensboro",
    "GSP": "Spartanburg",
    "GTF": "Great Falls",
    "GTR": "Columbus Golden Triangle（MS）",
    "GUC": "Gunnison",
    "GUM": "Guam",
    "GUW": "Atyrau",
    "GVA": "Geneva",
    "GYE": "Guayaquil",
    "GZT": "Gaziantep",
    "HAJ": "Hanover",
    "HAM": "Hamburg",
    "HAN": "Hanoi",
    "HAV": "Havana",
    "HBA": "Hobart",
    "HDN": "Steamboat Springs Hayden Yampa Valley",
    "HDY": "Hat Yai",
    "HEL": "Helsinki",
    "HIB": "Hibbing",
    "HIJ": "Hiroshima",
    "HKG": "Hongkong",
    "HKT": "Phuket",
    "HLN": "Helena",
    "HNL": "Honolulu",
    "HOU": "Houston",
    "HPN": "White Plains",
    "HSV": "Huntsville",
    "HTS": "Huntington",
    "HUY": "Humberside",
    "HYA": "Hyannis",
    "HYD": "Hyderabad",
    "IAD": "Washington Dulles",
    "IBZ": "Ibiza",
    "ICT": "Wichita",
    "IDA": "Idaho Falls",
    "IEV": "Kiev",
    "ILO": "Iloilo",
    "IND": "Indianapolis",
    "INL": "International Fall",
    "INN": "Innsbruck",
    "IPH": "Ipoh",
    "IPL": "Imperial",
    "ISB": "Islamabad",
    "ISP": "Islip",
    "IST": "Istanbul",
    "IYK": "Inyokem",
    "IZM": "Izmir",
    "JAC": "Jackson",
    "JAN": "Jackson",
    "JAX": "Jacksonville",
    "JED": "Jeddah",
    "JFK": "New York John F Kennedy",
    "JHB": "Johor Bahru",
    "JIB": "Djibouti",
    "JLN": "Joplin",
    "JNB": "Johannesburg",
    "JOG": "Yogyakarta",
    "JRO": "Kilimanjaro",
    "KAN": "Kano",
    "KBR": "Kota Bharu",
    "KBV": "Krabi",
    "KCH": "Kuching",
    "KGF": "Karaganda",
    "KHH": "Kaohsiung",
    "KHI": "Karachi",
    "KHV": "Khabarovsk",
    "KIJ": "Niigata",
    "KIV": "Chisinau",
    "KJA": "Krasnoyarsk",
    "KKC": "Khonkean",
    "KLO": "Kalibo",
    "KLU": "lagenfurt",
    "KMQ": "Komatsu",
    "KOA": "Kona",
    "KOJ": "Kagoshim",
    "KRK": "Krakow",
    "KRT": "Khartoum",
    "KSC": "Kosice",
    "KTM": "Kathmandu",
    "KTW": "Katowice",
    "KUA": "Kuantan",
    "KUF": "Samara",
    "KUL": "Kuala Lumpur",
    "KUO": "Kuopio",
    "KWI": "Kuwait",
    "KWJ": "Kwangju",
    "KYA": "Konya",
    "KZN": "Kazan",
    "LAD": "Luanda",
    "LAF": "Lafayette",
    "LAI": "Lannion",
    "LAN": "Lansing",
    "LAO": "Laoag",
    "LAS": "Las Vegas",
    "LAX": "Los Angeles",
    "LBA": "Leeds Bradford",
    "LBU": "Labuan",
    "LBV": "Libreville",
    "LCA": "Larnaca",
    "LCG": "La Coruna",
    "LCY": "London City Airport",
    "LDU": "Lahad Datu",
    "LEB": "Lebanon",
    "LED": "St Petersburg",
    "LEH": "Le Havre",
    "LEJ": "Leipzig-Halle",
    "LEN": "Leon",
    "LEX": "Lexington",
    "LFW": "Lome",
    "LGA": "New York La Guard",
    "LGK": "Langkawi",
    "LGP": "Legaspi",
    "LHE": "Lahore",
    "LHR": "London",
    "LIL": "Lille",
    "LIM": "Lima",
    "LIN": "Milan Linate",
    "LIS": "Lisbon",
    "LIT": "Little Rock",
    "LJU": "Ljubljana",
    "LKO": "Lucknow",
    "LMT": "Klamath Falls",
    "LNK": "lincoln",
    "LNZ": "Lina",
    "LON": "London",
    "LOS": "Lagos",
    "LPA": "Las Palmas",
    "LPQ": "Luang Prabang",
    "LRT": "Lorient",
    "LSE": "La Crosse",
    "LST": "Launceston",
    "LUX": "Luxembourg",
    "LWS": "Lewiston",
    "LXR": "Luxor",
    "LYH": "Lynchburg",
    "LYS": "Lyon",
    "MAA": "Chennai",
    "MAD": "Madrid",
    "MAH": "Menorca",
    "MAN": "Manchester",
    "MBL": "Manistee",
    "MBS": "Saginaw",
    "MCI": "Kansas City",
    "MCO": "Orlando International",
    "MCT": "Muscat",
    "MCW": "Mason City",
    "MDC": "Manado",
    "MDT": "Harrisburg",
    "MDW": "Chicago Midway Airport",
    "MEI": "Meridian",
    "MEL": "Melbourne",
    "MEM": "Memphis",
    "MES": "Medan",
    "MEX": "Mexico City",
    "MFM": "Macau",
    "MFR": "Medford",
    "MGM": "Montgomery",
    "MHD": "Mashhad",
    "MHT": "Manchester",
    "MIA": "Miami",
    "MIL": "Milan",
    "MKC": "Kansas city",
    "MKE": "Milwaukee",
    "MKG": "Muskegon",
    "MKL": "Jackson",
    "MLA": "Malta",
    "MLE": "Male",
    "MLI": "Moline",
    "MLU": "Monroe",
    "MLX": "Malatya",
    "MME": "Teesside",
    "MNL": "Manila",
    "MOB": "Mobile",
    "MOD": "Modesto",
    "MOT": "Minot",
    "MOW": "Moscow",
    "MPL": "Montpellier",
    "MQT": "Marquette",
    "MRS": "Marseille",
    "MRU": "Mauritius",
    "MRY": "Monterey",
    "MSL": "Muscie Shoals",
    "MSN": "Madison",
    "MSO": "Missoula",
    "MSP": "Minneapolis",
    "MSQ": "Minsk",
    "MST": "Maastricht",
    "MSY": "New Orleans",
    "MTJ": "Montrose",
    "MUC": "Munich",
    "MVD": "Montevideo",
    "MWH": "Moses Lake",
    "MXP": "Milan Malpensa",
    "MYJ": "Matsuyama",
    "MYY": "Miri",
    "NAN": "Nadi",
    "NAP": "Naples",
    "NBO": "Nairobi",
    "NCE": "Nice",
    "NCL": "Newcastle",
    "NCY": "Annecy",
    "NDJ": "Ndjamena",
    "NGO": "Nagoya",
    "NGS": "Nagasaki",
    "NIM": "Niamey",
    "NKC": "Nouakchott",
    "NTE": "Nantes",
    "NUE": "Nuremberg",
    "NWI": "Norwich",
    "NYC": "New York",
    "OAK": "Oakland",
    "ODS": "Odessa",
    "OGG": "Kahului",
    "OKA": "Okinawa",
    "OKC": "Oklahoma Ciyt",
    "OKJ": "Okayama",
    "OMA": "Omaha",
    "ONT": "Ontario",
    "OOL": "Gold Coast",
    "OPO": "Porto",
    "ORD": "Chicago O'Hare",
    "ORF": "Norfolk",
    "ORK": "Cork",
    "ORL": "Orlando",
    "OSA": "Osaka",
    "OSL": "Oslo",
    "OTH": "North Bend",
    "OUA": "Ouagadougou",
    "OUL": "Oulu",
    "OVD": "Asturias",
    "OWB": "Owensboro",
    "OXR": "Oxnard",
    "PAH": "Paducah",
    "PAP": "Port au Prince",
    "PAR": "Paris",
    "CDG": "Paris",
    "ORY": "Paris",
    "LBG": "Paris",
    "PBI": "West Palm Beach",
    "PBM": "Paramaribo",
    "PDG": "Padang",
    "PDT": "Pendleton",
    "PDX": "Portland",
    "PEE": "Perm",
    "PEG": "Perugia",
    "PEN": "Penang",
    "PER": "Perth",
    "PEW": "Peshawar",
    "PFN": "Panama City",
    "PFO": "Paphos",
    "PGF": "Perpignan",
    "PHC": "Port Harcourt",
    "PHL": "Philadelphia",
    "PHX": "Phoenix",
    "PIA": "Peoria",
    "PIB": "Laurel",
    "PIH": "Pocatello",
    "PIR": "Pierre",
    "PIT": "Pittsburg",
    "PIX": "Pico Island",
    "PLM": "Palembang",
    "PLN": "Pellston",
    "PLZ": "Port Elizabeth",
    "PMF": "Parma",
    "PMI": "Palma Mallorca",
    "PMO": "Palermo",
    "PNH": "Phnom Penh",
    "PNR": "Pointe Noire",
    "PNS": "Pensacola",
    "POZ": "Pozanan",
    "PPS": "Puerto Princesa",
    "PQI": "Presque Isle",
    "PRG": "Prague",
    "PRN": "Pristina",
    "PSA": "Pisa",
    "PSC": "Pasco",
    "PSP": "Palm Springs",
    "PSR": "Pescara",
    "PTP": "Pointe a Pitre",
    "PUF": "Pau",
    "PUJ": "Punta Cana",
    "PUS": "Pusan",
    "PUW": "Pullman",
    "PVD": "Providence",
    "PWM": "Portland",
    "QXG": "Angers",
    "RAK": "Marrakech",
    "RAP": "Rapid City",
    "RBA": "Rabat",
    "RDD": "Redding",
    "RDM": "Redmond",
    "RDU": "Raleigh",
    "RDZ": "Rodez",
    "REG": "Reggio Calabria",
    "REK": "Reykjavik",
    "REP": "Siem Reap",
    "RFD": "Rockford",
    "RGN": "Yangon",
    "RHI": "Rhinelander",
    "RIC": "Richmond",
    "RIO": "Rio De Janeiro",
    "RIX": "Riga",
    "RMI": "Rimini",
    "RNO": "Reno",
    "RNS": "Rennes",
    "ROA": "Roanoke",
    "ROC": "Rochester",
    "ROM": "Rome",
    "RST": "Rochester",
    "RSW": "Fort Myers",
    "RTM": "Rotterdam",
    "RUH": "Riyadh",
    "RUN": "St Denis De La Re",
    "RVN": "Rovaniemi",
    "RXS": "Roxa",
    "SAH": "Sanaa",
    "SAN": "San Diego",
    "SAO": "Sao Paulo",
    "SAT": "San Antonio",
    "SAV": "Savannah",
    "SBA": "Santa Barbara",
    "SBN": "South Bend",
    "SBP": "San Luis Obispo",
    "SBW": "Sibu",
    "SCE": "State College",
    "SCL": "Santiago",
    "SCQ": "Santiago De Compo",
    "SDF": "Louisville",
    "SDJ": "Senda",
    "SDK": "Sandakan",
    "SDQ": "Santo Domingo",
    "SEA": "Seattle",
    "SEL": "Selou",
    "SEZ": "Mahe Island",
    "SFO": "San Francisco",
    "SFQ": "Sanliurfa",
    "SGF": "Springfield",
    "SGN": "Ho Chi Minh City",
    "SHR": "Sheridan",
    "SHV": "Shreveport",
    "SIN": "Singapore",
    "SIP": "Simferopol",
    "SJC": "San Jose",
    "SJJ": "Sarajevo",
    "SKG": "Thessaloniki",
    "SKP": "Skopje",
    "SLC": "Salt lake City",
    "SLE": "Salem",
    "SMF": "Sacramento",
    "SMX": "Santa Maria",
    "SNA": "Orange County",
    "SNN": "Shannon",
    "SOC": "Solo City",
    "SOF": "Sofia",
    "SOU": "Southampton",
    "SPI": "Springfield IL",
    "SPK": "Sapporo",
    "SPN": "Saipan",
    "SPU": "Split",
    "SRG": "Semarang",
    "SSG": "Malabo",
    "STC": "St. Cloud",
    "STL": "St.Louis",
    "STO": "Stockholm",
    "STR": "Stuttgart",
    "SUB": "Surabaya",
    "SUF": "Lamezia Terme",
    "SUN": "Sun Valley",
    "SUW": "Superior",
    "SUX": "Sioux City",
    "SVG": "Stavanger",
    "SVQ": "Seville",
    "SWF": "Newburgh",
    "SXB": "Strasbourg",
    "SXM": "Saint Maarten",
    "SYD": "Sydney",
    "SYR": "Syracuse",
    "SZF": "Samsun Carsamba",
    "SZG": "Salzburg",
    "TAC": "Tacloban",
    "TAE": "Taegu",
    "TAG": "Tagbilaran",
    "TAS": "Tashkent",
    "TBS": "Tbilisi",
    "TCI": "Tenerife",
    "TGD": "Podgorica",
    "TGG": "Kuala Terengganu",
    "THR": "Tehran",
    "TIA": "Tirana",
    "TIP": "Tripoli",
    "TKU": "Turku",
    "TLL": "Tallinn",
    "TLS": "Toulouse",
    "TLV": "Telaviv",
    "TMP": "Tampere",
    "TNR": "Antananarivo",
    "TOL": "Toledo",
    "TPA": "Tampa",
    "TPE": "Taipei",
    "TRD": "Trondheim",
    "TRF": "Sandefjord",
    "TRI": "Bristol",
    "TRN": "Turin",
    "TRS": "Trieste",
    "TRV": "Thiruvananthapura",
    "TRZ": "Tiruchirapally",
    "TSE": "Astana",
    "TSR": "Timisoara",
    "TST": "Trang",
    "TUF": "Tours",
    "TUG": "Tuguegarao",
    "TUL": "Tulsa",
    "TUN": "Tunis",
    "TUP": "Tupelo",
    "TUS": "Tucson",
    "TVC": "Traverse City",
    "TVF": "Thief River Falls",
    "TWF": "Twins Falls",
    "TWU": "Tawau",
    "TYO": "Tokyo",
    "NRT": "Tokyo",
    "TYS": "Knoxville",
    "TZX": "Trabzon",
    "UIN": "Quincy",
    "UIO": "Quito",
    "UPG": "Ujung Pandang",
    "URT": "Surat Thani",
    "USM": "Koh Samui",
    "UTH": "Udon Thani",
    "VAA": "Vaasa",
    "VAN": "Van",
    "VAR": "Varna",
    "VCE": "Venice",
    "VFA": "Victoria Falls",
    "VGO": "vigo",
    "VIE": "Vienna",
    "VIS": "Visalia",
    "VLC": "Valencia",
    "VLL": "Valladolid",
    "VNO": "Vilnius",
    "VPS": "Valparaiso",
    "VRN": "Verona",
    "VTE": "Vientiane",
    "VVO": "Vladivostok",
    "WAS": "Washington",
    "WAW": "Warsaw",
    "WDH": "Windhoek",
    "WLG": "Wellington",
    "WNP": "Naga",
    "WRO": "Wroclaw",
    "XDB": "Lille",
    "XOP": "Poitiers",
    "XYD": "Lyon",
    "YAM": "Sault Ste-Marie",
    "YAO": "Yaounde",
    "YBL": "Campbell River",
    "YCD": "Nanaimo",
    "YCH": "Miramichi",
    "YDF": "Deer Lake",
    "YEG": "Edmonton",
    "YFC": "Fredericton",
    "YGK": "Kingston",
    "YHZ": "Halifax",
    "YKA": "Kamloops",
    "YKM": "Yakima",
    "YLW": "Kelowna",
    "YNG": "Youngstown",
    "YOW": "Ottawa",
    "YPR": "Prince Rupert",
    "YQB": "Quebec",
    "YQG": "Windsor",
    "YQM": "Moncton",
    "YQQ": "Comox",
    "YQR": "Regina",
    "YQT": "Thunder Bay",
    "YQY": "Sydney",
    "YSB": "Sudbury",
    "YSJ": "Sanit John",
    "YTO": "Toronto",
    "YUL": "Montreal",
    "YUM": "Yuma",
    "YVO": "Val d'or",
    "YVR": "Vancouver",
    "YWG": "Winnipeg",
    "YXE": "Saskatoon",
    "YXS": "Prince George",
    "YXT": "Terrace",
    "YYC": "Calgary",
    "YYF": "Penticton",
    "YYG": "Charlottetown",
    "YYJ": "Victoria",
    "YYR": "Goose Bay",
    "YYT": "St,John's",
    "YYZ": "Toronto",
    "YZR": "Sarnia",
    "ZAG": "Zagreb",
    "ZAM": "Zamboanga",
    "ZLN": "Le Mans",
    "ZQN": "Queenstown",
    "ZRH": "Zurich",
    "ZTM": "Shamattawa",
    "ZYR": "Brussels",
}

