#!/usr/bin/python
# -*- coding: UTF-8 -*-

CITY_IATA = {
    "Abidjan": "ABJ",
    "Abuja": "ABV",
    "Accra": "ACC",
    "Addis Ababa": "ADD",
    "Algiers": "ALG",
    "Antananarivo": "TNR",
    "Arba Minch": "AMH",
    "Assosa": "ASO",
    "Axum": "AXU",
    "Bahir Dar": "BJR",
    "Bamako": "BKO",
    "Bangui": "BGF",
    "Brazzaville": "BZV",
    "Bujumbura": "BJM",
    "Cairo": "CAI",
    "Cape Town": "CPT",
    "Casablanca": "CMN",
    "Conakry": "CKY",
    "Cotonou": "COO",
    "Dakar": "DKR",
    "Dar es Salaam": "DAR",
    "Dire Dawa": "DIR",
    "Djibouti": "JIB",
    "Douala": "DLA",
    "Durban": "DUR",
    "Entebbe/Kampala": "EBB",
    "Freetown": "FNA",
    "Gaborone": "GBE",
    "Gambela": "GMB",
    "Gondar": "GDQ",
    "Harare": "HRE",
    "Hargeisa": "HGA",
    "Jijiga": "JIJ",
    "Jimma": "JIM",
    "Johannesburg": "JNB",
    "Juba": "JUB",
    "Kano": "KAN",
    "Khartoum": "KRT",
    "Kigali": "KGL",
    "Kilimanjaro": "JRO",
    "Kinshasa": "FIH",
    "Kisumu": "KIS",
    "Lagos": "LOS",
    "Lalibela": "LLI",
    "Libreville": "LBV",
    "Lilongwe": "LLW",
    "Lomé": "LFW",
    "Lusaka": "LUN",
    "Malabo": "SSG",
    "Maputo": "MPM",
    "Mauritius": "MRU",
    "Mekele": "MQX",
    "Mogadishu": "MGQ",
    "Mombasa": "MBA",
    "Monrovia": "ROB",
    "Mwanza": "MWZ",
    "N'Djamena": "NDJ",
    "Nairobi": "NBO",
    "Niamey": "NIM",
    "Nosy Be": "NOS",
    "Nouakchott": "NKC",
    "Ouagadougou": "OUA",
    "Port Harcourt": "PHC",
    "Tripoli": "TIP",
    "Tunis": "TUN",
    "Windhoek": "WDH",
    "Yaoundé": "YAO",
    "Zanzibar": "ZNZ", "Aalborg": "AAL",  
    "Aberdeen": "ABR", 
    "Aberseen": "ABZ", 
    "Abidjan": "ABJ",  
    "Abu Dhabi": "AUH",
    "Abuja": "ABV",    
    "Accra": "ACC",
    "Adana": "ADA",
    "Addis Ababa": "ADD",
    "Adelaide": "ADL",
    "Ahmedabad": "AMD",
    "Ajaccio": "AJA",
    "Akron": "CAK",
    "Albany": "ALB",
    "Albuquerque": "ABQ",
    "Alexandria": "ESF",
    "Alexandriai": "ALY",
    "Alghero": "AHO",
    "Algiers": "ALG",
    "Alicante": "ALC",
    "Allentown": "ABE",
    "Almaty": "ALA",
    "Alor Setar": "AOR",
    "Altenrhein": "ACH",
    "Amarillo": "AMA",
    "Amman": "AMM",
    "Amsterdam": "AMS",
    "Anchorage": "ANC",
    "Ancona": "AOI",
    "Angers": "QXG",
    "Ankara": "ANK",
    "Annecy": "NCY",
    "Antalya": "AYT",
    "Antananarivo": "TNR",
    "Antwerp": "ANR",
    "Appleton": "ATW",
    "Arba Minch": "AMH",
    "Arcata": "ACV",
    "Aruba": "AUA",
    "Ashgabat": "ASB",
    "Asmara": "ASM",
    "Aspen": "ASE",
    "Assosa": "ASO",
    "Astana": "TSE",
    "Asturias": "OVD",
    "Athens": "ATH",
    "Atlanta": "ATL",
    "Atlantic City": "AIY",
    "Atyrau": "GUW",
    "Auckland": "AKL",
    "Augusta": "AUG",
    "Austin": "AUS",
    "Avignon": "AVN",
    "Axum": "AXU",
    "Bacolod": "BCD",
    "Bahir Dar": "BJR",
    "Bahrain": "BAH",
    "Bakersfield": "BFL",
    "Baku": "BAK",
    "Bali": "DPS",
    "Balikpapan": "BPN",
    "Baltimore": "BWI",
    "Bamako": "BKO",
    "Bandar Seribegaw": "BWN",
    "Bangalore": "BLR",
    "Bangkok": "BKK",
    "Bangor": "BGR",
    "Bangui": "BGF",
    "Barcelona": "BCN",
    "Bari": "BRI",
    "Basel": "BSL",
    "Bastia": "BIA",
    "Baton Rouge": "BTR",
    "Beirut": "BEY",
    "Belfast": "BFS",
    "Belfast City Apt": "BHD",
    "Belgrade": "BEG",
    "Bellinghan": "BLI",
    "Bemidji": "BJI",
    "Bergen": "BGO",
    "Berlin": "BER",
    "Berne": "BRN",
    "Biarritz": "BIQ",
    "Bilbao": "BIO",
    "Billings": "BIL",
    "Billund": "BLL",
    "Binghamton": "BGM",
    "Bintulu": "BTU",
    "Birmingham": "BHX",
    "Bishkek": "FRU",
    "Bloomington": "BMI",
    "Bodrum Milas": "BJV",
    "Bogota": "BOG",
    "Boise": "BOI",
    "Bologna": "BLQ",
    "Bonaire": "BON",
    "Bordeauxtz": "BOD",
    "Boston": "BOS",
    "Bozeman": "BZN",
    "Brainerd": "BRD",
    "Brazzaville": "BZV",
    "Bremen": "BRE",
    "Brest": "BES",
    "Brindisi": "BDS",
    "Brisbane": "BNE",
    "Bristol": "TRI",
    "Brussel": "BRU",
    "Brussels": "ZYR",
    "Bucharest": "BUH",
    "Budapest": "BUD",
    "Buenos Aires": "EZE",
    "Buffalo": "BUF",
    "Bujumbura": "BJM",
    "Burbank": "BUR",
    "Burlington": "BTV",
    "Butte": "BTM",
    "Butuan": "BXU",
    "Caen": "CFR",
    "Cagayan De Oro": "CGY",
    "Cagliari": "CAG",
    "Cairns": "CNS",
    "Cairo": "CAI",
    "Calcutta": "CCU",
    "Calgary": "YYC",
    "Calvi": "CLY",
    "Campbell River": "YBL",
    "Canberra": "CBR",
    "Cape Town": "CPT",
    "Caracas": "CCS",
    "Cardiff": "CWL",
    "Casablanca": "CMN",
    "Catania": "CTA",
    "Cayenne": "CAY",
    "Cebu": "CEB",
    "Cedar Rapids": "CID",
    "Chadron": "CDR",
    "Champaign": "CMI",
    "Charieston": "CRW",
    "Charleston,SC": "CHS",
    "Charlotte": "CLT",
    "Charlottesville": "CHO",
    "Charlottetown": "YYG",
    "Chattanooga": "CHA",
    "Cheju": "CJU",
    "Chennai": "MAA",
    "Cheong Ju City": "CJJ",
    "Chiang Mai": "CNX",
    "Chiang Rai": "CEI",
    "Chicago": "CHI",
    "Chicago Midway Airport": "MDW",
    "Chicago O'Hare": "ORD",
    "Chico": "CIC",
    "Chisinau": "KIV",
    "Chittagong": "CGP",
    "Christchurch": "CHC",
    "Cincinnati": "CVG",
    "Cleveland": "CLE",
    "Cochin": "COK",
    "Cologne": "CGN",
    "Colombo": "CMB",
    "Colorado Springs": "COS",
    "Columbia": "CAE",
    "Columbus": "CMH",
    "Columbus Golden Triangle（MS）": "GTR",
    "Columbus（GA）": "CSG",
    "Comox": "YQQ",
    "Conakry": "CKY",
    "Copenhagen": "CPH",
    "Cork": "ORK",
    "Cotabato": "CBO",
    "Cotonou": "COO",
    "Crescent City": "CEC",
    "Crotone": "CRV",
    "Curacao": "CUR",
    "Dakar": "DKR",
    "Dalaman": "DLM",
    "Dallas": "DFW",
    "Damascus": "DAM",
    "Dammam": "DMM",
    "Dar Es Salaam": "DAR",
    "Dar es Salaam": "DAR",
    "Darwin": "DRW",
    "Davao": "DVO",
    "Dayton": "DAY",
    "Deer Lake": "YDF",
    "Delhi": "DEL",
    "Denizli": "DNZ",
    "Denver": "DEN",
    "Des Moines": "DSM",
    "Detroit": "DTW",
    "Dhaka": "DAC",
    "Dipolog": "DPL",
    "Dire Dawa": "DIR",
    "Diyarbakir": "DIY",
    "Djibouti": "JIB",
    "Dodge City": "DDC",
    "Doha": "DOH",
    "Dothan": "DHN",
    "Douala": "DLA",
    "Dresden": "DRS",
    "Dubai": "DXB",
    "Dublin": "DUB",
    "Dubrovnik": "DBV",
    "Dubugui": "DBQ",
    "Duluth": "DLH",
    "Dumaguete": "DGT",
    "Dunedin": "DUD",
    "Durban": "DUR",
    "Dusseldorf": "DUS",
    "Eau Claire": "EAU",
    "Edinburgh": "EDI",
    "Edmonton": "YEG",
    "Edremit/Korfez": "EDO",
    "Eindhoven": "EIN",
    "Entebbe/Kampala": "EBB",
    "Ercan": "ECN",
    "Erie": "ERI",
    "Erzurum": "ERZ",
    "Escanada": "ESC",
    "Eugene": "EUG",
    "Evansville": "EVV",
    "Fairbanks": "FAI",
    "Fargo": "FAR",
    "Faro": "FAO",
    "Fayetteville": "FYV",
    "Flint": "FNT",
    "Florencei": "FLR",
    "Fort Dodge": "FOD",
    "Fort Lauderdale": "FLL",
    "Fort Myers": "RSW",
    "Fort Smith": "FSM",
    "Fort Wayne": "FWA",
    "Fort de France": "FDF",
    "Frankfurt": "FRA",
    "Fredericton": "YFC",
    "Freetown": "FNA",
    "Fresno": "FAT",
    "Friedrichshafen": "FDH",
    "Fuerteventura": "FUE",
    "Fukuoka": "FUK",
    "Fukushima": "FKS",
    "Funchal": "FNC",
    "Gaborone": "GBE",
    "Gambela": "GMB",
    "Gaziantep": "GZT",
    "Gdansk": "GDN",
    "General Santos": "GES",
    "Geneva": "GVA",
    "Genoa": "GOA",
    "Glasgow": "GLA",
    "Goa": "GOI",
    "Gold Coast": "OOL",
    "Gondar": "GDQ",
    "Goose Bay": "YYR",
    "Gothenburg": "GOT",
    "Grand Canyon": "GCN",
    "Grand Forks": "GFK",
    "Grand Junction": "GJT",
    "Grand Rapids": "GRR",
    "Graz": "GRZ",
    "Great Falls": "GTF",
    "Green Bay": "GRB",
    "Greensboro": "GSO",
    "Greenville": "GLH",
    "Grenoble": "GNB",
    "Guam": "GUM",
    "Guayaquil": "GYE",
    "Gulfport": "GPT",
    "Gunnison": "GUC",
    "Halifax": "YHZ",
    "Hamburg": "HAM",
    "Hancock": "CMX",
    "Hanoi": "HAN",
    "Hanover": "HAJ",
    "Harare": "HRE",
    "Hargeisa": "HGA",
    "Harrisburg": "MDT",
    "Hartford Bradley": "BDL",
    "Hat Yai": "HDY",
    "Havana": "HAV",
    "Helena": "HLN",
    "Helsinki": "HEL",
    "Hibbing": "HIB",
    "Hiroshima": "HIJ",
    "Ho Chi Minh City": "SGN",
    "Hobart": "HBA",
    "Hongkong": "HKG",
    "Honolulu": "HNL",
    "Houston": "HOU",
    "Humberside": "HUY",
    "Huntington": "HTS",
    "Huntsville": "HSV",
    "Hyannis": "HYA",
    "Hyderabad": "HYD",
    "Ibiza": "IBZ",
    "Idaho Falls": "IDA",
    "Iloilo": "ILO",
    "Imperial": "IPL",
    "Indianapolis": "IND",
    "Innsbruck": "INN",
    "International Fall": "INL",
    "Inyokem": "IYK",
    "Ipoh": "IPH",
    "Islamabad": "ISB",
    "Islip": "ISP",
    "Istanbul": "IST",
    "Izmir": "IZM",
    "Izmir Adnan Mende": "ADB",
    "Jackson": "MKL",
    "Jacksonville": "JAX",
    "Jakarta": "CGK",
    "Jeddah": "JED",
    "Jijiga": "JIJ",
    "Jimma": "JIM",
    "Joensuu": "EUS",
    "Johannesburg": "JNB",
    "Johor Bahru": "JHB",
    "Joplin": "JLN",
    "Juba": "JUB",
    "Kagoshim": "KOJ",
    "Kahului": "OGG",
    "Kalamazoo": "AZO",
    "Kalibo": "KLO",
    "Kalispell": "FCA",
    "Kamloops": "YKA",
    "Kano": "KAN",
    "Kansas City": "MCI",
    "Kansas city": "MKC",
    "Kaohsiung": "KHH",
    "Karachi": "KHI",
    "Karaganda": "KGF",
    "Kathmandu": "KTM",
    "Katowice": "KTW",
    "Kayseri": "ASR",
    "Kazan": "KZN",
    "Kelowna": "YLW",
    "Khabarovsk": "KHV",
    "Khartoum": "KRT",
    "Khonkean": "KKC",
    "Kiev": "IEV",
    "Kigali": "KGL",
    "Kilimanjaro": "JRO",
    "Kingston": "YGK",
    "Kinshasa": "FIH",
    "Kisumu": "KIS",
    "Klamath Falls": "LMT",
    "Knoxville": "TYS",
    "Koh Samui": "USM",
    "Komatsu": "KMQ",
    "Kona": "KOA",
    "Konya": "KYA",
    "Kosice": "KSC",
    "Kota Bharu": "KBR",
    "Kota Kinabalu": "BKI",
    "Kozhikode": "CCJ",
    "Krabi": "KBV",
    "Krakow": "KRK",
    "Krasnoyarsk": "KJA",
    "Kuala Lumpur": "KUL",
    "Kuala Terengganu": "TGG",
    "Kuantan": "KUA",
    "Kuching": "KCH",
    "Kuopio": "KUO",
    "Kuwait": "KWI",
    "Kwangju": "KWJ",
    "La Coruna": "LCG",
    "La Crosse": "LSE",
    "Labuan": "LBU",
    "Lafayette": "LAF",
    "Lagos": "LOS",
    "Lahad Datu": "LDU",
    "Lahore": "LHE",
    "Lalibela": "LLI",
    "Lamezia Terme": "SUF",
    "Langkawi": "LGK",
    "Lannion": "LAI",
    "Lansing": "LAN",
    "Lanzarota": "ACE",
    "Laoag": "LAO",
    "Larnaca": "LCA",
    "Las Palmas": "LPA",
    "Las Vegas": "LAS",
    "Launceston": "LST",
    "Laurel": "PIB",
    "Le Havre": "LEH",
    "Le Mans": "ZLN",
    "Lebanon": "LEB",
    "Leeds Bradford": "LBA",
    "Legaspi": "LGP",
    "Leipzig-Halle": "LEJ",
    "Leon": "LEN",
    "Lewiston": "LWS",
    "Lexington": "LEX",
    "Libreville": "LBV",
    "Lille": "XDB",
    "Lilongwe": "LLW",
    "Lima": "LIM",
    "Lina": "LNZ",
    "Lisbon": "LIS",
    "Little Rock": "LIT",
    "Ljubljana": "LJU",
    "Lome": "LFW",
    "Lomé": "LFW",
    "London": "LON",
    "London City Airport": "LCY",
    "Lorient": "LRT",
    "Los Angeles": "LAX",
    "Louisville": "SDF",
    "Luanda": "LAD",
    "Luang Prabang": "LPQ",
    "Lucknow": "LKO",
    "Lusaka": "LUN",
    "Luxembourg": "LUX",
    "Luxor": "LXR",
    "Lynchburg": "LYH",
    "Lyon": "XYD",
    "Maastricht": "MST",
    "Macau": "MFM",
    "Madison": "MSN",
    "Madrid": "MAD",
    "Mahe Island": "SEZ",
    "Malabo": "SSG",
    "Malaga": "AGP",
    "Malatya": "MLX",
    "Male": "MLE",
    "Malta": "MLA",
    "Manado": "MDC",
    "Manchester": "MHT",
    "Manila": "MNL",
    "Manistee": "MBL",
    "Maputo": "MPM",
    "Marquette": "MQT",
    "Marrakech": "RAK",
    "Marseille": "MRS",
    "Mashhad": "MHD",
    "Mason City": "MCW",
    "Mataram": "AMI",
    "Matsuyama": "MYJ",
    "Mauritius": "MRU",
    "Medan": "MES",
    "Medford": "MFR",
    "Mekele": "MQX",
    "Melbourne": "MEL",
    "Memphis": "MEM",
    "Menorca": "MAH",
    "Meridian": "MEI",
    "Metz-Nancy": "ETZ",
    "Mexico City": "MEX",
    "Miami": "MIA",
    "Milan": "MIL",
    "Milan Linate": "LIN",
    "Milan Malpensa": "MXP",
    "Milwaukee": "MKE",
    "Minneapolis": "MSP",
    "Minot": "MOT",
    "Minsk": "MSQ",
    "Miramichi": "YCH",
    "Miri": "MYY",
    "Missoula": "MSO",
    "Mobile": "MOB",
    "Modesto": "MOD",
    "Mogadishu": "MGQ",
    "Mohammed V": "CMN",
    "Moline": "MLI",
    "Mombasa": "MBA",
    "Moncton": "YQM",
    "Monroe": "MLU",
    "Monrovia": "ROB",
    "Monterey": "MRY",
    "Montevideo": "MVD",
    "Montgomery": "MGM",
    "Montpellier": "MPL",
    "Montreal": "YUL",
    "Montrose": "MTJ",
    "Moscow": "MOW",
    "Moses Lake": "MWH",
    "Mumbai": "BOM",
    "Munich": "MUC",
    "Munich Augsburg": "AGB",
    "Munster": "FMO",
    "Muscat": "MCT",
    "Muscie Shoals": "MSL",
    "Muskegon": "MKG",
    "Mwanza": "MWZ",
    "N'Djamena": "NDJ",
    "Nadi": "NAN",
    "Naga": "WNP",
    "Nagasaki": "NGS",
    "Nagoya": "NGO",
    "Nairobi": "NBO",
    "Nanaimo": "YCD",
    "Nantes": "NTE",
    "Nantucket": "ACK",
    "Naples": "NAP",
    "Nashville": "BNA",
    "Ndjamena": "NDJ",
    "New Orleans": "MSY",
    "New York": "NYC",
    "New York John F Kennedy": "JFK",
    "New York La Guard": "LGA",
    "Newark": "EWR",
    "Newburgh": "SWF",
    "Newcastle": "NCL",
    "Niamey": "NIM",
    "Nice": "NCE",
    "Niigata": "KIJ",
    "Nizhniy Novgorod": "GOJ",
    "Norfolk": "ORF",
    "North Bend": "OTH",
    "Norwich": "NWI",
    "Nosy Be": "NOS",
    "Nouakchott": "NKC",
    "Nuremberg": "NUE",
    "Oakland": "OAK",
    "Odessa": "ODS",
    "Okayama": "OKJ",
    "Okinawa": "OKA",
    "Oklahoma Ciyt": "OKC",
    "Omaha": "OMA",
    "Ontario": "ONT",
    "Orange County": "SNA",
    "Orlando": "ORL",
    "Orlando International": "MCO",
    "Osaka": "OSA",
    "Oslo": "OSL",
    "Ottawa": "YOW",
    "Ouagadougou": "OUA",
    "Oulu": "OUL",
    "Owensboro": "OWB",
    "Oxnard": "OXR",
    "Padang": "PDG",
    "Paducah": "PAH",
    "Palembang": "PLM",
    "Palermo": "PMO",
    "Palm Springs": "PSP",
    "Palma Mallorca": "PMI",
    "Panama City": "PFN",
    "Paphos": "PFO",
    "Paramaribo": "PBM",
    "Paris": "LBG",
    "Parma": "PMF",
    "Pasco": "PSC",
    "Pau": "PUF",
    "Pellston": "PLN",
    "Penang": "PEN",
    "Pendleton": "PDT",
    "Pensacola": "PNS",
    "Penticton": "YYF",
    "Peoria": "PIA",
    "Perm": "PEE",
    "Perpignan": "PGF",
    "Perth": "PER",
    "Perugia": "PEG",
    "Pescara": "PSR",
    "Peshawar": "PEW",
    "Philadelphia": "PHL",
    "Phnom Penh": "PNH",
    "Phoenix": "PHX",
    "Phuket": "HKT",
    "Pico Island": "PIX",
    "Pierre": "PIR",
    "Pisa": "PSA",
    "Pittsburg": "PIT",
    "Pocatello": "PIH",
    "Podgorica": "TGD",
    "Pointe Noire": "PNR",
    "Pointe a Pitre": "PTP",
    "Poitiers": "XOP",
    "Port Angeles": "CLM",
    "Port Elizabeth": "PLZ",
    "Port Harcourt": "PHC",
    "Port au Prince": "PAP",
    "Portland": "PWM",
    "Porto": "OPO",
    "Pozanan": "POZ",
    "Prague": "PRG",
    "Presque Isle": "PQI",
    "Prince George": "YXS",
    "Prince Rupert": "YPR",
    "Pristina": "PRN",
    "Providence": "PVD",
    "Puerto Princesa": "PPS",
    "Pullman": "PUW",
    "Punta Cana": "PUJ",
    "Pusan": "PUS",
    "Quebec": "YQB",
    "Queenstown": "ZQN",
    "Quincy": "UIN",
    "Quito": "UIO",
    "Rabat": "RBA",
    "Raleigh": "RDU",
    "Rapid City": "RAP",
    "Redding": "RDD",
    "Redmond": "RDM",
    "Reggio Calabria": "REG",
    "Regina": "YQR",
    "Rennes": "RNS",
    "Reno": "RNO",
    "Reykjavik": "REK",
    "Rhinelander": "RHI",
    "Richmond": "RIC",
    "Riga": "RIX",
    "Rimini": "RMI",
    "Rio De Janeiro": "RIO",
    "Riyadh": "RUH",
    "Roanoke": "ROA",
    "Rochester": "RST",
    "Rockford": "RFD",
    "Rodez": "RDZ",
    "Rome": "ROM",
    "Rotterdam": "RTM",
    "Rovaniemi": "RVN",
    "Roxa": "RXS",
    "Sacramento": "SMF",
    "Saginaw": "MBS",
    "Saint Maarten": "SXM",
    "Saipan": "SPN",
    "Salem": "SLE",
    "Salt lake City": "SLC",
    "Salzburg": "SZG",
    "Samara": "KUF",
    "Samsun Carsamba": "SZF",
    "San Antonio": "SAT",
    "San Diego": "SAN",
    "San Diego Carlsbad": "CLD",
    "San Francisco": "SFO",
    "San Jose": "SJC",
    "San Luis Obispo": "SBP",
    "Sanaa": "SAH",
    "Sandakan": "SDK",
    "Sandefjord": "TRF",
    "Sanit John": "YSJ",
    "Sanliurfa": "SFQ",
    "Santa Barbara": "SBA",
    "Santa Maria": "SMX",
    "Santiago": "SCL",
    "Santiago De Compo": "SCQ",
    "Santo Domingo": "SDQ",
    "Sao Paulo": "SAO",
    "Sapporo": "SPK",
    "Sarajevo": "SJJ",
    "Sarnia": "YZR",
    "Saskatoon": "YXE",
    "Sault Ste-Marie": "YAM",
    "Savannah": "SAV",
    "Seattle": "SEA",
    "Selou": "SEL",
    "Semarang": "SRG",
    "Senda": "SDJ",
    "Seville": "SVQ",
    "Shamattawa": "ZTM",
    "Shannon": "SNN",
    "Sheridan": "SHR",
    "Shreveport": "SHV",
    "Sibu": "SBW",
    "Siem Reap": "REP",
    "Simferopol": "SIP",
    "Singapore": "SIN",
    "Sious Falls": "FSD",
    "Sioux City": "SUX",
    "Skopje": "SKP",
    "Sofia": "SOF",
    "Solo City": "SOC",
    "South Bend": "SBN",
    "Southampton": "SOU",
    "Spartanburg": "GSP",
    "Split": "SPU",
    "Spokane": "GEG",
    "Springfield": "SGF",
    "Springfield IL": "SPI",
    "St Denis De La Re": "RUN",
    "St Petersburg": "LED",
    "St,John's": "YYT",
    "St. Cloud": "STC",
    "St.Louis": "STL",
    "State College": "SCE",
    "Stavanger": "SVG",
    "Steamboat Springs Hayden Yampa Valley": "HDN",
    "Stockholm": "STO",
    "Strasbourg": "SXB",
    "Stuttgart": "STR",
    "Sudbury": "YSB",
    "Sun Valley": "SUN",
    "Superior": "SUW",
    "Surabaya": "SUB",
    "Surat Thani": "URT",
    "Sydney": "YQY",
    "Syracuse": "SYR",
    "Tacloban": "TAC",
    "Taegu": "TAE",
    "Tagbilaran": "TAG",
    "Taipei": "TPE",
    "Tallinn": "TLL",
    "Tampa": "TPA",
    "Tampere": "TMP",
    "Tashkent": "TAS",
    "Tawau": "TWU",
    "Tbilisi": "TBS",
    "Teesside": "MME",
    "Tehran": "THR",
    "Telaviv": "TLV",
    "Tenerife": "TCI",
    "Terrace": "YXT",
    "Thessaloniki": "SKG",
    "Thief River Falls": "TVF",
    "Thiruvananthapura": "TRV",
    "Thunder Bay": "YQT",
    "Timisoara": "TSR",
    "Tirana": "TIA",
    "Tiruchirapally": "TRZ",
    "Tokyo": "NRT",
    "Toledo": "TOL",
    "Toronto": "YYZ",
    "Toulouse": "TLS",
    "Tours": "TUF",
    "Trabzon": "TZX",
    "Trang": "TST",
    "Traverse City": "TVC",
    "Trieste": "TRS",
    "Tripoli": "TIP",
    "Trondheim": "TRD",
    "Tucson": "TUS",
    "Tuguegarao": "TUG",
    "Tulsa": "TUL",
    "Tunis": "TUN",
    "Tupelo": "TUP",
    "Turin": "TRN",
    "Turku": "TKU",
    "Twins Falls": "TWF",
    "Udon Thani": "UTH",
    "Ujung Pandang": "UPG",
    "Vaasa": "VAA",
    "Vail": "EGE",
    "Val d'or": "YVO",
    "Valencia": "VLC",
    "Valladolid": "VLL",
    "Valparaiso": "VPS",
    "Van": "VAN",
    "Vancouver": "YVR",
    "Varna": "VAR",
    "Venice": "VCE",
    "Verona": "VRN",
    "Victoria": "YYJ",
    "Victoria Falls": "VFA",
    "Vienna": "VIE",
    "Vientiane": "VTE",
    "Vilnius": "VNO",
    "Visalia": "VIS",
    "Vladivostok": "VVO",
    "Walla Walla": "ALW",
    "Warsaw": "WAW",
    "Washington": "WAS",
    "Washington Dulles": "IAD",
    "Washington Ronald": "DCA",
    "Waterloo": "ALO",
    "Watertown": "ATY",
    "Wausau": "CWA",
    "Wellington": "WLG",
    "Wenatchee": "EAT",
    "West Palm Beach": "PBI",
    "White Plains": "HPN",
    "Wichita": "ICT",
    "Wilkes-Barre": "AVP",
    "Windhoek": "WDH",
    "Windsor": "YQG",
    "Winnipeg": "YWG",
    "Wroclaw": "WRO",
    "Yakima": "YKM",
    "Yangon": "RGN",
    "Yaounde": "YAO",
    "Yaoundé": "YAO",
    "Yerevan": "EVN",
    "Yogyakarta": "JOG",
    "Youngstown": "YNG",
    "Yuma": "YUM",
    "Zagreb": "ZAG",
    "Zamboanga": "ZAM",
    "Zanzibar": "ZNZ",
    "Zurich": "ZRH",
    "lagenfurt": "KLU",
    "lincoln": "LNK",
    "vigo": "VGO",
}
